#### Municipality Name Edits

#fixing unmerged names

#2000
cands_00 <- raw_00 %>% group_by(Município) %>%
  summarise(count=n()) %>%
  rename("2000" = "count") %>%
  mutate(city = stri_trans_general(Município, "Latin-ASCII")) %>%
  select(2:3) %>%
  mutate(city = tolower(city)) %>%
  mutate(city = str_replace_all(city, c('aguas lindas'= 'aguas lindas de goias',
                                        'almerim'= 'almeirim',
                                        'alta floresta do oeste'= 'alta floresta d\'oeste',
                                        'alto da boa vista'= 'alto boa vista',
                                        'americo de campos dos goytacazes'= 'americo de campos',
                                        'amparo do sao francisco'= 'amparo de sao francisco',
                                        'aparecida d oeste'= 'aparecida d\'oeste',
                                        'aparecida do tabuado'= 'aparecida do taboado',
                                        'apicum acu'= 'apicum-acu',
                                        'arco iris'= 'arco-iris',
                                        'armacao de buzios'= 'armacao dos buzios',
                                        'arraial do cabo de santo agostinho'= 'arraial do cabo',
                                        'bady bassit'= 'bady bassitt',
                                        'balneario de barra do sul'= 'balneario barra do sul',
                                        'balneario de camboriu'= 'balneario camboriu',
                                        'bataguacu'= 'bataguassu',
                                        'bataipora'= 'bataypora',
                                        'bernadino de campos'= 'bernardino de campos',
                                        'boa vista de ramos'= 'boa vista do ramos',
                                        'cabo'= 'cabo de santo agostinho',
                                        'cabo de santo agostinho frio'= 'cabo frio',
                                        'cabo de santo agostinho verde'= 'cabo verde',
                                        'campos'= 'campos dos goytacazes',
                                        'campos dos goytacazes altos'= 'campos altos',
                                        'campos dos goytacazes belos'= 'campos belos',
                                        'campos dos goytacazes borges'= 'campos borges',
                                        'campos dos goytacazes de julio'= 'campos de julio',
                                        'campos dos goytacazes do jordao'= 'campos do jordao',
                                        'campos dos goytacazes gerais'= 'campos gerais',
                                        'campos dos goytacazes lindos'= 'campos lindos',
                                        'campos dos goytacazes novos'= 'campos novos',
                                        'campos dos goytacazes novos paulista'= 'campos novos paulista',
                                        'campos dos goytacazes sales'= 'campos sales',
                                        'campos dos goytacazes verdes'= 'campos verdes',
                                        'capitao de campos dos goytacazes'= 'capitao de campos',
                                        'ceara mirim'= 'ceara-mirim',
                                        'caninde do sao francisco'= 'caninde de sao francisco',
                                        'cerro-cora'= 'cerro cora',
                                        'chapada da areia'= 'chapada de areia',
                                        'chiapeta'= 'chiapetta',
                                        'conceicao da pedra'= 'conceicao das pedras',
                                        'conceicao do lago acu'= 'conceicao do lago-acu',
                                        'conselheiro mayrinck'= 'conselheiro mairinck',
                                        'dep irapuan pinheiro'= 'deputado irapuan pinheiro',
                                        'diamante do oeste'= 'diamante d\'oeste',
                                        'dias d avila'= 'dias d\'avila',
                                        'dores de campos dos goytacazes'= 'dores de campos',
                                        'embu das artes guacu'= 'embu-guacu',
                                        'eldorado do carajas'= 'eldorado dos carajas',
                                        'embu'= 'embu das artes',
                                        'embu guacu'= 'embu-guacu',
                                        'entre ijuis'= 'entre-ijuis',
                                        'espigao d\'oeste'= 'espigao do oeste',
                                        'estrela d oeste'= 'estrela d\'oeste',
                                        'euzebio'= 'eusebio',
                                        'fernando pedrosa'= 'fernando pedroza',
                                        'figueiropoles d\'oeste'= 'figueiropolis d\'oeste',
                                        'gouvea'= 'gouveia',
                                        'governador edson lobao'= 'governador edison lobao',
                                        'grangeiro'= 'granjeiro',
                                        'grao para'= 'grao-para',
                                        'guajara mirim'= 'guajara-mirim',
                                        'guarani d oeste'= 'guarani d\'oeste',
                                        'herval do oeste'= 'herval d\'oeste',
                                        'igarape acu'= 'igarape-acu',
                                        'ipaucu'= 'ipaussu',
                                        'itabirinha de mantena'= 'itabirinha',
                                        'itaguage'= 'itaguaje',
                                        'itamogi'= 'itamoji',
                                        'itapejara do oeste'= 'itapejara d\'oeste',
                                        'itaporanga d ajuda'= 'itaporanga d\'ajuda',
                                        'jaboatao'= 'jaboatao dos guararapes',
                                        'ji parana'= 'ji-parana',
                                        'juty'= 'juti',
                                        'lageado grande'= 'lajeado grande',
                                        'lagoa d anta'= 'lagoa d\'anta',
                                        'luiz alves'= 'luis alves',
                                        'luis domingues do maranhao'= 'luis domingues',
                                        'luisiania'= 'luiziania',
                                        'mae d agua'= 'mae d\'agua',
                                        'manuel urbano'= 'manoel urbano',
                                        'moji guacu'= 'mogi guacu',
                                        'moji mirim'= 'mogi mirim',
                                        'moreira salles'= 'moreira sales',
                                        'munhoz de mello'= 'munhoz de melo',
                                        'nao me toque'= 'nao-me-toque',
                                        'nova bandeirante'= 'nova bandeirantes',
                                        'novo ayrao'= 'novo airao',
                                        'olho d agua'= 'olho d\'agua',
                                        'olho d agua das cunhas'= 'olho d\'agua das cunhas',
                                        'olho d agua das flores'= 'olho d\'agua das flores',
                                        'olho d agua do casado'= 'olho d\'agua do casado',
                                        'olho d agua grande'= 'olho d\'agua grande',
                                        'olho dagua do piaui'= 'olho d\'agua do piaui',
                                        'olhos dagua'= 'olhos d\'agua',
                                        'oliveira do tocantins'= 'oliveira de fatima',
                                        'palmeira d oeste'= 'palmeira d\'oeste',
                                        'parati'= 'paraty',
                                        'pati do alferes'= 'paty do alferes',
                                        'pau darco do piaui'= 'pau d\'arco do piaui',
                                        'perola d oeste'= 'perola d\'oeste',
                                        'pindare mirim'= 'pindare-mirim',
                                        'pingo dagua'= 'pingo d\'agua',
                                        'piracununga'= 'pirassununga',
                                        'porto esperediao'= 'porto esperidiao',
                                        'poxoreo'= 'poxoreu',
                                        'salmorao'= 'salmourao',
                                        'santa barbara d oeste'= 'santa barbara d\'oeste',
                                        'santa clara d oeste'= 'santa clara d\'oeste',
                                        'santa cruz do monte castelo'= 'santa cruz de monte castelo',
                                        'santa izabel do ivai'= 'santa isabel do ivai',
                                        'santa izabel do para'= 'santa isabel do para',
                                        'santa maria do jetiba'= 'santa maria de jetiba',
                                        'santa rita d oeste'= 'santa rita d\'oeste',
                                        'santa rita do ibitipoca'= 'santa rita de ibitipoca',
                                        'santa ana do itarare'= 'santana do itarare',
                                        'santo antonio da posse'= 'santo antonio de posse',
                                        'sao caetano'= 'sao caitano',
                                        'sao felipe d oeste'= 'sao felipe d\'oeste',
                                        'sao joao d alianca'= 'sao joao d\'alianca',
                                        'sao joao do pau d alho'= 'sao joao do pau d\'alho',
                                        'sao jorge d oeste'= 'sao jorge d\'oeste',
                                        'sao jose de campestre'= 'sao jose do campestre',
                                        'sao jose do brejo cruz'= 'sao jose do brejo do cruz',
                                        'sao luis gonzaga'= 'sao luiz gonzaga',
                                        'sao luiz do anaua'= 'sao luiz',
                                        'sao miguel de touros'= 'sao miguel do gostoso',
                                        'sao raimundo da doca bezerra'= 'sao raimundo do doca bezerra',
                                        'sao seb. de lagoa de roca'= 'sao sebastiao de lagoa de roca',
                                        'sao tome das letras'= 'sao thome das letras',
                                        'sapucai mirim'= 'sapucai-mirim',
                                        'sao valerio da natividade'= 'sao valerio',
                                        'sem-peixe'= 'sem peixe',
                                        'senador la roque'= 'senador la rocque',
                                        'sitio d abadia'= 'sitio d\'abadia',
                                        'sud menucci'= 'sud mennucci',
                                        'suzanopolis'= 'suzanapolis',
                                        'tanque d arca'= 'tanque d\'arca',
                                        'tejussuoca'= 'tejucuoca',
                                        'tapura'= 'tapurah',
                                        'tome acu'= 'tome-acu',
                                        'valparaizo'= 'valparaiso de goias',
                                        'varre e sai'= 'varre-sai',
                                        'venha ver'= 'venha-ver',
                                        'vila bela stssma trindade'= 'vila bela da santissima trindade',
                                        'vizeu'= 'viseu',
                                        'xique xique'= 'xique-xique'))) %>%
  mutate(city = str_replace_all(city, c('americo de campos dos goytacazes'= 'americo de campos',
                                        'arraial do cabo de santo agostinho'= 'arraial do cabo',
                                        'bernardino de campos dos goytacazes' = 'bernardino de campos',
                                        'embu das artes guacu' = 'embu-guacu',
                                        'itamoji' = 'itamogi',
                                        'itapurah' = 'itapura',
                                        'itapurahnga' = 'itapuranga',
                                        'japaratinga'= 'japaratynga',
                                        'lima campos dos goytacazes'= 'lima campos',
                                        'mario campos dos goytacazes'= 'mario campos',
                                        'martinho campos dos goytacazes'= 'martinho campos',
                                        'monte alegre dos campos dos goytacazes'= 'monte alegre dos campos',
                                        'itamaraca'= 'ilha de itamaraca',
                                        'picarras' = 'balneario picarras',
                                        'pindorama de goias' = 'pindorama do tocantins',
                                        'sao caitano de odivelas' = 'sao caetano de odivelas',
                                        'sao caitano do sul' = 'sao caetano do sul',
                                        'sao goncalo dos campos dos goytacazes' = 'sao goncalo dos campos',
                                        'sao jose dos campos dos goytacazes' = 'sao jose dos campos',
                                        'sao luiz gonzaga do maranhao' = 'sao luis gonzaga do maranhao',
                                        'sao miguel dos campos dos goytacazes' = 'sao miguel dos campos',
                                        'siqueira campos dos goytacazes'= 'siqueira campos',
                                        'amapari' = 'pedra branca do amapari',
                                        'senador catunda' = 'catunda',
                                        'quatro marcos' = 'sao jose dos quatro marcos')))



#2004
cands_04 <- raw_04 %>% group_by(Município) %>%
  summarise(count=n()) %>%
  rename("2004" = "count") %>%
  mutate(city = stri_trans_general(Município, "Latin-ASCII")) %>%
  select(2:3) %>%
  mutate(city = tolower(city)) %>%
  mutate(city = str_replace_all(city, c('aguas lindas'= 'aguas lindas de goias',
                                        'alta floresta do oeste'= 'alta floresta d\'oeste',
                                        'amparo do sao francisco'= 'amparo de sao francisco',
                                        'aparecida d oeste'= 'aparecida d\'oeste',
                                        'aparecida do tabuado'= 'aparecida do taboado',
                                        'apicum acu'= 'apicum-acu',
                                        'arco iris'= 'arco-iris',
                                        'americo de campos dos goytacazes'= 'americo de campos',
                                        'armacao de buzios'= 'armacao dos buzios',
                                        'arraial do cabo de santo agostinho'= 'arraial do cabo',
                                        'bady bassit'= 'bady bassitt',
                                        'bataguacu'= 'bataguassu',
                                        'bataipora'= 'bataypora',
                                        'boa vista de ramos'= 'boa vista do ramos',
                                        'cabo'= 'cabo de santo agostinho',
                                        'cabo de santo agostinho frio'= 'cabo frio',
                                        'cabo de santo agostinho verde'= 'cabo verde',
                                        'campos'= 'campos dos goytacazes',
                                        'campos dos goytacazes altos'= 'campos altos',
                                        'campos dos goytacazes belos'= 'campos belos',
                                        'campos dos goytacazes borges'= 'campos borges',
                                        'campos dos goytacazes de julio'= 'campos de julio',
                                        'campos dos goytacazes do jordao'= 'campos do jordao',
                                        'campos dos goytacazes gerais'= 'campos gerais',
                                        'campos dos goytacazes lindos'= 'campos lindos',
                                        'campos dos goytacazes novos'= 'campos novos',
                                        'campos dos goytacazes novos paulista'= 'campos novos paulista',
                                        'campos dos goytacazes sales'= 'campos sales',
                                        'campos dos goytacazes verdes'= 'campos verdes',
                                        'capitao de campos dos goytacazes'= 'capitao de campos',
                                        'ceara mirim'= 'ceara-mirim',
                                        'caninde do sao francisco'= 'caninde de sao francisco',
                                        'cerro-cora'= 'cerro cora',
                                        'chiapeta'= 'chiapetta',
                                        'conceicao da pedra'= 'conceicao das pedras',
                                        'conceicao do lago acu'= 'conceicao do lago-acu',
                                        'conselheiro mayrinck'= 'conselheiro mairinck',
                                        'darcynopolis'= 'darcinopolis',
                                        'dep irapuan pinheiro'= 'deputado irapuan pinheiro',
                                        'diamante do oeste'= 'diamante d\'oeste',
                                        'dias d avila'= 'dias d\'avila',
                                        'dores de campos dos goytacazes'= 'dores de campos',
                                        'embu das artes guacu'= 'embu-guacu',
                                        'eldorado do carajas'= 'eldorado dos carajas',
                                        'embu'= 'embu das artes',
                                        'embu guacu'= 'embu-guacu',
                                        'entre ijuis'= 'entre-ijuis',
                                        'espigao d\'oeste'= 'espigao do oeste',
                                        'estrela d oeste'= 'estrela d\'oeste',
                                        'euzebio'= 'eusebio',
                                        'fernando pedrosa'= 'fernando pedroza',
                                        'gouvea'= 'gouveia',
                                        'governador edson lobao'= 'governador edison lobao',
                                        'grangeiro'= 'granjeiro',
                                        'grao para'= 'grao-para',
                                        'guajara mirim'= 'guajara-mirim',
                                        'guarani d oeste'= 'guarani d\'oeste',
                                        'igarape acu'= 'igarape-acu',
                                        'ipaucu'= 'ipaussu',
                                        'itaguage'= 'itaguaje',
                                        'itapejara do oeste'= 'itapejara d\'oeste',
                                        'itaporanga d ajuda'= 'itaporanga d\'ajuda',
                                        'jaboatao'= 'jaboatao dos guararapes',
                                        'ji parana'= 'ji-parana',
                                        'juty'= 'juti',
                                        'lagoa d anta'= 'lagoa d\'anta',
                                        'luis domingues do maranhao'= 'luis domingues',
                                        'luisiania'= 'luiziania',
                                        'mae d agua'= 'mae d\'agua',
                                        'manuel urbano'= 'manoel urbano',
                                        'moji guacu'= 'mogi guacu',
                                        'moji mirim'= 'mogi mirim',
                                        'moreira salles'= 'moreira sales',
                                        'munhoz de mello'= 'munhoz de melo',
                                        'nao me toque'= 'nao-me-toque',
                                        'nova bandeirante'= 'nova bandeirantes',
                                        'novo ayrao'= 'novo airao',
                                        'olho d agua'= 'olho d\'agua',
                                        'olho d agua das cunhas'= 'olho d\'agua das cunhas',
                                        'olho d agua das flores'= 'olho d\'agua das flores',
                                        'olho d agua do casado'= 'olho d\'agua do casado',
                                        'olho d agua grande'= 'olho d\'agua grande',
                                        'olho dagua do piaui'= 'olho d\'agua do piaui',
                                        'olhos dagua'= 'olhos d\'agua',
                                        'palmeira d oeste'= 'palmeira d\'oeste',
                                        'parati'= 'paraty',
                                        'pati do alferes'= 'paty do alferes',
                                        'pau darco do piaui'= 'pau d\'arco do piaui',
                                        'perola d oeste'= 'perola d\'oeste',
                                        'pindare mirim'= 'pindare-mirim',
                                        'pingo dagua'= 'pingo d\'agua',
                                        'piracununga'= 'pirassununga',
                                        'poxoreo'= 'poxoreu',
                                        'salmorao'= 'salmourao',
                                        'santa barbara d oeste'= 'santa barbara d\'oeste',
                                        'santa clara d oeste'= 'santa clara d\'oeste',
                                        'santa cruz do monte castelo'= 'santa cruz de monte castelo',
                                        'santa izabel do ivai'= 'santa isabel do ivai',
                                        'santa izabel do para'= 'santa isabel do para',
                                        'santa maria do jetiba'= 'santa maria de jetiba',
                                        'santa rita d oeste'= 'santa rita d\'oeste',
                                        'santa rita do ibitipoca'= 'santa rita de ibitipoca',
                                        'santo antonio da posse'= 'santo antonio de posse',
                                        'sao caetano'= 'sao caitano',
                                        'sao felipe d oeste'= 'sao felipe d\'oeste',
                                        'sao joao d alianca'= 'sao joao d\'alianca',
                                        'sao joao do pau d alho'= 'sao joao do pau d\'alho',
                                        'sao jorge d oeste'= 'sao jorge d\'oeste',
                                        'sao jose de campestre'= 'sao jose do campestre',
                                        'sao jose do brejo cruz'= 'sao jose do brejo do cruz',
                                        'sao luis gonzaga'= 'sao luiz gonzaga',
                                        'sao luiz do anaua'= 'sao luiz',
                                        'sao miguel de touros'= 'sao miguel do gostoso',
                                        'sao raimundo da doca bezerra'= 'sao raimundo do doca bezerra',
                                        'sao seb. de lagoa de roca'= 'sao sebastiao de lagoa de roca',
                                        'sao tome das letras'= 'sao thome das letras',
                                        'sapucai mirim'= 'sapucai-mirim',
                                        'sao valerio da natividade'= 'sao valerio',
                                        'sem-peixe'= 'sem peixe',
                                        'senador la roque'= 'senador la rocque',
                                        'sitio d abadia'= 'sitio d\'abadia',
                                        'sud menucci'= 'sud mennucci',
                                        'suzanopolis'= 'suzanapolis',
                                        'tanque d arca'= 'tanque d\'arca',
                                        'tejussuoca'= 'tejucuoca',
                                        'tome acu'= 'tome-acu',
                                        'valparaizo'= 'valparaiso de goias',
                                        'varre e sai'= 'varre-sai',
                                        'venha ver'= 'venha-ver',
                                        'vizeu'= 'viseu',
                                        'xique xique'= 'xique-xique'))) %>%
  mutate(city = str_replace_all(city, c('americo de campos dos goytacazes'= 'americo de campos',
                                        'arraial do cabo de santo agostinho'= 'arraial do cabo',
                                        'bernardino de campos dos goytacazes' = 'bernardino de campos',
                                        'embu das artes guacu' = 'embu-guacu',
                                        'humberto de campos dos goytacazes' = 'humberto de campos',
                                        'itamoji' = 'itamogi',
                                        'japaratinga'= 'japaratynga',
                                        'lima campos dos goytacazes'= 'lima campos',
                                        'mario campos dos goytacazes'= 'mario campos',
                                        'martinho campos dos goytacazes'= 'martinho campos',
                                        'monte alegre dos campos dos goytacazes'= 'monte alegre dos campos',
                                        'itamaraca'= 'ilha de itamaraca',
                                        'sao caitano de odivelas' = 'sao caetano de odivelas',
                                        'sao caitano do sul' = 'sao caetano do sul',
                                        'sao goncalo dos campos dos goytacazes' = 'sao goncalo dos campos',
                                        'sao jose dos campos dos goytacazes' = 'sao jose dos campos',
                                        'sao luiz gonzaga do maranhao' = 'sao luis gonzaga do maranhao',
                                        'sao miguel dos campos dos goytacazes' = 'sao miguel dos campos',
                                        'siqueira campos dos goytacazes'= 'siqueira campos',
                                        'amapari' = 'pedra branca do amapari',
                                        'senador catunda' = 'catunda')))

#2008
cands_08 <- raw_08 %>% group_by(Município) %>%
  summarise(count=n()) %>%
  rename("2008" = "count") %>%
  mutate(city = stri_trans_general(Município, "Latin-ASCII")) %>%
  select(2:3) %>%
  mutate(city = tolower(city)) %>%
  mutate(city = str_replace_all(city, c('alta floresta do oeste'= 'alta floresta d\'oeste',
                                        'brasopolis'= 'brazopolis',
                                        'embu'= 'embu das artes',
                                        'embu das artes-guacu'= 'embu-guacu',
                                        'nova brasilandia do oeste'= 'nova brasilandia d\'oeste',
                                        'parati'= 'paraty',
                                        'quinjingue'= 'quijingue',
                                        'sao felipe do oeste'= 'sao felipe d\'oeste',
                                        'sao valerio do tocantins'= 'sao valerio'))) %>%
  mutate(city = str_replace_all(city, c('japaratinga'= 'japaratynga',
                                        'itamaraca'= 'ilha de itamaraca',
                                        'agua branca do amapari' = 'pedra branca do amapari')))
  

#2012
cands_12 <- raw_12 %>% group_by(Município) %>%
  summarise(count=n()) %>%
  rename("2012" = "count") %>%
  mutate(city = stri_trans_general(Município, "Latin-ASCII")) %>%
  select(2:3) %>%
  mutate(city = tolower(city)) %>%
  mutate(city = str_replace_all(city, c('alta floresta do oeste' = 'alta floresta d\'oeste',
                                        'nova brasilandia do oeste' = 'nova brasilandia d\'oeste',
                                        'quinjingue' = 'quijingue',
                                        'sao felipe do oeste' = 'sao felipe d\'oeste',
                                        'sao valerio da natividade' = 'sao valerio',
                                        'pacaembu'= 'pacaembu das artes',
                                        'paratinga'= 'paratynga')))

#2016 
cands_16 <- raw_16 %>% group_by(Município) %>%
  summarise(count=n()) %>%
  rename("2016" = "count") %>%
  mutate(city = stri_trans_general(Município, "Latin-ASCII")) %>%
  select(2:3) %>%
  mutate(city = tolower(city)) %>%
  mutate(city = str_replace_all(city, c('arez' = 'ares', 
                                        'belem do sao francisco' = 'belem de sao francisco', 
                                        'camaca' = 'camacan', 
                                        'camacanri' = 'camacari', 
                                        'couto magalhaes'= 'couto de magalhaes', 
                                        'iguaracy'= 'iguaraci', 
                                        'itapaje'= 'itapage', 
                                        'machadinho d\'oeste'= 'machadinho do oeste', 
                                        'santa luzia d\'oeste'= 'santa luzia do oeste', 
                                        'sant\'ana do livramento'= 'santana do livramento', 
                                        'trajano de moraes'= 'trajano de morais'))) %>%
  mutate(city = str_replace_all(city, c('jacaresinho'= 'jacarezinho',
                                        'juares tavora'= 'juarez tavora',
                                        'luiz alves'= 'luis alves',
                                        'nazaresinho'= 'nazarezinho',
                                        'pacaembu'= 'pacaembu das artes',
                                        'paratinga'= 'paratynga',
                                        'tabocao'= 'fortaleza do tabocao')))

#2020
cands_20 <- raw_20 %>% group_by(Município) %>%
  summarise(count=n()) %>%
  rename("2020" = "count") %>%
  mutate(city = stri_trans_general(Município, "Latin-ASCII")) %>%
  select(2:3) %>%
  mutate(city = tolower(city)) %>%
  mutate(city = str_replace_all(city, c('arez' = 'ares',
                                        'belem do sao francisco' = 'belem de sao francisco',
                                        'camaca' = 'camacan',
                                        'camacanri' = 'camacari',
                                        'couto magalhaes' = 'couto de magalhaes',
                                        'iguaracy' = 'iguaraci',
                                        'itapaje' = 'itapage',
                                        'machadinho d\'oeste' = 'machadinho do oeste',
                                        'santa luzia d\'oeste' = 'santa luzia do oeste',
                                        'sant\'ana do livramento' = 'santana do livramento',
                                        'trajano de moraes' = 'trajano de morais'
                                        ))) %>%
  mutate(city = str_replace_all(city, c('jacaresinho'= 'jacarezinho',
                                        'juares tavora'= 'juarez tavora',
                                        'luiz alves'= 'luis alves',
                                        'nazaresinho'= 'nazarezinho',
                                        'pacaembu'= 'pacaembu das artes',
                                        'paratinga'= 'paratynga',
                                        'tabocao'= 'fortaleza do tabocao')))
  


